version: '3'

services:
  db:
    image: mysql:latest
    container_name: dbf

    environment:
      MYSQL_DATABASE: webapp_dbf
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_password

    ports:
      - "3307:3306"

    volumes:
      - dbdata:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pmaf

    environment: 
      PMA_HOST: dbf
      PMA_POST: 3306
      PMA_ARBITRARY: 1
        
    ports: 
      - 8080:80

  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./webapp/:/usr/webapp     

    ports:
      - 5000:5000

    #restart: always

volumes:
  dbdata:


# docker stop $(docker ps -aq)
# docker rm $(docker ps -aq)
# docker rmi $(docker images -aq)
# docker system prune 
# curl localhost:8080
# curl localhost:80


